I am not quite sure of what is needed of me here. This is what I could come up with.

In [2]:
import numpy as np

import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits = load_digits()

In [1]:
# Load dataset
from google.colab import files
uploaded = files.upload()

Saving mnist_train.csv to mnist_train.csv
Saving mnist_test.csv to mnist_test.csv


In [3]:
mnist = load_digits()
X = mnist.data
y = mnist.target

In [4]:
# Split the training data into a training and test set.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

I used 80% of the data for training and 20% for testing. I also set a random seed (random_state=42) so that I get the same split every time we run the code.

In [5]:
# Use the RandomForestClassifier from sklearn.ensemble to create a classification model
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier()

*   Pick one parameter to tune, and
explain why you chose this parameter.

Ans: I choose the number of trees (n_estimators) in the random forest. This parameter controls the number of decision trees in the ensemble, and a higher number can lead to better performance but also longer training times and higher memory usage.

In [6]:
# Pick one parameter to tune
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

RandomForestClassifier()

In [7]:
# Print the confusion matrix for your Random Forest model on the test set:
from sklearn.metrics import confusion_matrix

y_pred = clf.predict(X_test)
con_mat = confusion_matrix(y_test, y_pred)
print(con_mat)

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  2  0  0  0  0  0  0 28  0]
 [ 0  0  0  0  0  1  0  2  0 37]]


**Which classes the model struggles with the most?**

From the confusion matrix, we can see that the model struggles the most with classes 8 and 9. These two classes have the lowest precision and recall values, indicating that the model is less accurate at predicting these classes compared to the others. We may want to consider strategies to address this issue, such as collecting more data or balancing the class distribution in the training set.
